
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ealcbtnmofspramewvsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbGNidG5tb2ZzcHJhbWV3dnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDM2NzYsImV4cCI6MjA1ODExOTY3Nn0.01t5D_QWovsaiJLFc9RE0qKFgo9nTOIAmx9h6v2VfCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
